# Generated by Django 5.1.3 on 2025-02-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad ajustada (puede ser positiva o negativa)')),
                ('tipo', models.CharField(choices=[('merma', 'Merma'), ('exceso', 'Exceso'), ('ajuste', 'Ajuste Manual')], max_length=20, verbose_name='Tipo de ajuste')),
                ('razon', models.TextField(blank=True, null=True, verbose_name='Razón del ajuste')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha del ajuste')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('proveedor', models.CharField(max_length=100, verbose_name='Proveedor')),
                ('fecha', models.DateField(verbose_name='Fecha de la factura')),
                ('numero_factura', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Número de factura')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total sin IVA')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kilos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad en kilos')),
                ('cantidad_unidades', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Cantidad en Unidades')),
                ('costo_por_kilo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo por kilo')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo total')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle de factura',
                'verbose_name_plural': 'Detalles de facturas',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pedido')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del pedido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendedor', verbose_name='Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kilos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad en kilos')),
                ('cantidad_unidades', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad en Unidades')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta (por kilo)')),
                ('costo_por_kilo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo por kilo en la venta')),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de la venta')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Detalle del pedido',
                'verbose_name_plural': 'Detalles de pedidos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio_por_kilo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por kilo')),
                ('categoria', models.CharField(blank=True, choices=[('al vacio', 'Al Vacio'), ('congelado', 'Congelado')], max_length=50, null=True, verbose_name='Categoría')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado')], default='disponible', max_length=20, verbose_name='Estado del producto')),
                ('ajustesI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.ajusteinventario')),
                ('detalles_pedido', models.ManyToManyField(related_name='productos', through='core.DetallePedido', to='core.pedido', verbose_name='Detalles del pedido')),
                ('facturas_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.detallefactura')),
                ('ventas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.detallepedido')),
            ],
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='core.producto'),
        ),
        migrations.CreateModel(
            name='PagoVendedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del pago')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes_pagos/', verbose_name='Comprobante (Foto)')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pago')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Pago del Vendedor',
                'verbose_name_plural': 'Pagos de Vendedores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.vendedor'),
        ),
    ]
