# Generated by Django 5.1.3 on 2025-02-26 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_pago', models.DateField(verbose_name='Fecha de pago')),
                ('monto_del_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del pago')),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_factura', to='core.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Pago de Factura',
                'verbose_name_plural': 'Pagos de Facturas',
            },
        ),
    ]
