# Generated by Django 5.1.3 on 2025-02-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidades_kilos',
            field=models.IntegerField(verbose_name='Unidades disponibles'),
        ),
    ]
