# Generated by Django 5.1.3 on 2025-02-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entradaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproducto',
            name='cantidad_unidades',
            field=models.IntegerField(default=0),
        ),
    ]
