# Generated by Django 5.1.3 on 2025-02-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_entradaproducto_cantidad_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='margen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Margen'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='total_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total del costo'),
        ),
    ]
