# Generated by Django 5.1.3 on 2025-02-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_detallepedido_margen_detallepedido_total_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='costo_por_kilo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo por kilo en la venta'),
        ),
    ]
