# Generated by Django 5.1.3 on 2025-03-01 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='facturas',
            field=models.ManyToManyField(default=0, related_name='detalles_pedido', to='core.factura', verbose_name='Facturas'),
        ),
        migrations.AddField(
            model_name='entradaproducto',
            name='factura',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.factura'),
        ),
        migrations.CreateModel(
            name='FacturaDetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_unidades', models.IntegerField(default=0)),
                ('detallepedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detallepedido')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.factura')),
            ],
            options={
                'unique_together': {('detallepedido', 'factura')},
            },
        ),
    ]
