# Generated by Django 5.1.3 on 2025-03-01 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_detallepedido_facturas_entradaproducto_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproducto',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.factura'),
        ),
    ]
