# Generated by Django 5.1.3 on 2025-03-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_entradaproducto_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Reservado', 'Reservado'), ('Preparado', 'Preparado'), ('Anulado', 'Anulado'), ('Pagado', 'Pagado')], default='Reservado', max_length=20, verbose_name='Estado del pedido'),
        ),
    ]
