# Generated by Django 5.1.3 on 2025-03-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad_kilos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Cantidad en kilos'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de la venta'),
        ),
    ]
